-- ---------------------------------------------------------------------------------------------------------------------------------------------
-- ------------------------------------------------------  Data Definition Language ------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------------------

DROP SCHEMA IF EXISTS trabajo;
CREATE SCHEMA trabajo DEFAULT CHARACTER SET utf8;
USE trabajo;

-- MySQL Script generated by MySQL Workbench
-- Tue Jan 13 21:43:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`SEDE_CANONICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`SEDE_CANONICA` (
  `direccion` VARCHAR(45) NOT NULL,
  `estilo_arquitectonico_predominante` VARCHAR(45) NULL,
  `fecha_construccion` VARCHAR(45) NULL,
  PRIMARY KEY (`direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HERMANDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`HERMANDAD` (
  `nombre` VARCHAR(45) NOT NULL,
  `cuota_anual` INT NOT NULL,
  `año_fundacional` VARCHAR(45) NULL,
  `nombre_hdad_originada` VARCHAR(45) NULL,
  `direccion_sede` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`),
  INDEX `direccion_sede_idx` (`direccion_sede` ASC),
  INDEX `fk_nombre_hdad_originada_idx` (`nombre_hdad_originada` ASC),
  CONSTRAINT `direccion_sede`
    FOREIGN KEY (`direccion_sede`)
    REFERENCES `trabajo`.`SEDE_CANONICA` (`direccion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_nombre_hdad_originada`
    FOREIGN KEY (`nombre_hdad_originada`)
    REFERENCES `trabajo`.`HERMANDAD` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`ROL` (
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOMBRE_COLOQUIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`NOMBRE_COLOQUIAL` (
  `nombre_coloquial` VARCHAR(45) NOT NULL,
  `nombre_oficial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_coloquial`, `nombre_oficial`),
  INDEX `nombre_oficial_idx` (`nombre_oficial` ASC) ,
  CONSTRAINT `fk_nombre_oficial`
    FOREIGN KEY (`nombre_oficial`)
    REFERENCES `trabajo`.`HERMANDAD` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`RESIDIA_EN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`RESIDIA_EN` (
  `nombre_hdad` VARCHAR(45) NOT NULL,
  `direccion_sede` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_hdad`, `direccion_sede`),
  INDEX `direccion_sede_idx` (`direccion_sede` ASC),
  CONSTRAINT `fk_nombre_hdad`
    FOREIGN KEY (`nombre_hdad`)
    REFERENCES `trabajo`.`HERMANDAD` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_sede`
    FOREIGN KEY (`direccion_sede`)
    REFERENCES `trabajo`.`SEDE_CANONICA` (`direccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EPOCA_HISTORICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`EPOCA_HISTORICA` (
  `periodo` VARCHAR(45) NOT NULL,
  `fechas` VARCHAR(45) NULL,
  PRIMARY KEY (`periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DESARROLLO_DURANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`DESARROLLO_DURANTE` (
  `periodo_epoca` VARCHAR(45) NOT NULL,
  `direccion_sede` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`periodo_epoca`, `direccion_sede`),
  INDEX `direccion_sede_idx` (`direccion_sede` ASC),
  CONSTRAINT `fk_periodo_epoca`
    FOREIGN KEY (`periodo_epoca`)
    REFERENCES `trabajo`.`EPOCA_HISTORICA` (`periodo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_direccion_sede_desarrollo`
    FOREIGN KEY (`direccion_sede`)
    REFERENCES `trabajo`.`SEDE_CANONICA` (`direccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HERMANDAD_PROCESIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`HERMANDAD_PROCESIONAL` (
  `nombre_hdad_procesional` VARCHAR(45) NOT NULL,
  `tiempo_en_calle` VARCHAR(45) NULL,
  `advocacion` VARCHAR(45) NULL,
  `corte` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre_hdad_procesional`),
  CONSTRAINT `fk_nombre_hdad_procesional`
    FOREIGN KEY (`nombre_hdad_procesional`)
    REFERENCES `trabajo`.`HERMANDAD` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROCESION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`PROCESION` (
  `motivo` VARCHAR(45) NOT NULL,
  `extraordinariedad` VARCHAR(45) NULL,
  PRIMARY KEY (`motivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REALIZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`REALIZA` (
  `nombre_hdad_procesional_realiza` VARCHAR(45) NOT NULL,
  `motivo_procesional` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_hdad_procesional_realiza`, `motivo_procesional`),
  INDEX `motivo_procesional_idx` (`motivo_procesional` ASC),
  CONSTRAINT `fk_nombre_hdad_procesional_realiza`
    FOREIGN KEY (`nombre_hdad_procesional_realiza`)
    REFERENCES `trabajo`.`HERMANDAD_PROCESIONAL` (`nombre_hdad_procesional`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_motivo_procesional`
    FOREIGN KEY (`motivo_procesional`)
    REFERENCES `trabajo`.`PROCESION` (`motivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DIA_PROCESIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`DIA_PROCESIONAL` (
  `dia_SS_estival` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dia_SS_estival`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`PERSONA` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARTICIPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`PARTICIPA` (
  `dni_persona_participante` VARCHAR(45) NOT NULL,
  `dia_SS_estival` VARCHAR(45) NOT NULL,
  `motivo_procesion` VARCHAR(45) NOT NULL,
  `rol_participacion` VARCHAR(45) NOT NULL,
  `importe_papeleta_sitio` INT NULL,
  PRIMARY KEY (`dni_persona_participante`, `dia_SS_estival`,`motivo_procesion`),
  INDEX `motivo_procesion_idx` (`motivo_procesion` ASC),
  INDEX `dni_persona_idx` (`dni_persona_participante` ASC),
  INDEX `rol_participacion_idx` (`rol_participacion` ASC),
  CONSTRAINT `fk_motivo_procesion`
    FOREIGN KEY (`motivo_procesion`)
    REFERENCES `trabajo`.`PROCESION` (`motivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dia_SS_estival`
    FOREIGN KEY (`dia_SS_estival`)
    REFERENCES `trabajo`.`DIA_PROCESIONAL` (`dia_SS_estival`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dni_persona_participante`
    FOREIGN KEY (`dni_persona_participante`)
    REFERENCES `trabajo`.`PERSONA` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rol_participacion`
    FOREIGN KEY (`rol_participacion`)
    REFERENCES `trabajo`.`ROL` (`categoria`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ES_HERMANO_DE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`ES_HERMANO_DE` (
  `numero_hermano` VARCHAR(45) NOT NULL,
  `nombre_hdad_es_hermano` VARCHAR(45) NOT NULL,
  `dni_hermano` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_hdad_es_hermano`, `dni_hermano`),
  UNIQUE INDEX `unique_numhermano_hdad` (`numero_hermano` ASC, `nombre_hdad_es_hermano` ASC),
  INDEX `fk_nombre_persona_idx` (`dni_hermano` ASC),
  CONSTRAINT `fk_nombre_hdad_es_hermano`
    FOREIGN KEY (`nombre_hdad_es_hermano`)
    REFERENCES `trabajo`.`HERMANDAD` (`nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dni_hermano`
    FOREIGN KEY (`dni_hermano`)
    REFERENCES `trabajo`.`PERSONA` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IMPLICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`IMPLICA` (
  `nombre_hdad_implicada` VARCHAR(45) NOT NULL,
  `categoria_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_hdad_implicada`, `categoria_rol`),
  INDEX `categoria_rol_idx` (`categoria_rol` ASC),
  CONSTRAINT `fk_nombre_hdad_implicada`
    FOREIGN KEY (`nombre_hdad_implicada`)
    REFERENCES `trabajo`.`HERMANDAD` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_rol`
    FOREIGN KEY (`categoria_rol`)
    REFERENCES `trabajo`.`ROL` (`categoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOMENCLATURA_CIUDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajo`.`NOMENCLATURA_CIUDAD` (
  `nombre` VARCHAR(45) NOT NULL,
  `comunidad` VARCHAR(45) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`, `comunidad`),
  INDEX `periodo_epoca_idx` (`periodo` ASC),
  CONSTRAINT `fk_periodo_epoca_ciudad`
    FOREIGN KEY (`periodo`)
    REFERENCES `trabajo`.`EPOCA_HISTORICA` (`periodo`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `trabajo`.`DETALLE_NOMENCLATURA` (
  `nombre_ciudad` VARCHAR(45) NOT NULL,
  `comunidad_ciudad` VARCHAR(45) NOT NULL,
  `etimologia` VARCHAR(45) NULL,
  `tipo_fuente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_ciudad`, `comunidad_ciudad`,`tipo_fuente`),
  CONSTRAINT `fk_detalle_nomenclatura`
    FOREIGN KEY (`nombre_ciudad` , `comunidad_ciudad`)
    REFERENCES `trabajo`.`NOMENCLATURA_CIUDAD` (`nombre` , `comunidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE) 
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--  O la fecha de nacimiento no está insertada y es null, o si aparece, tiene que ser anterior al día de hoy

ALTER TABLE PERSONA 
ADD CONSTRAINT chk_fecha_nacimiento_rango 
CHECK (fecha_nacimiento IS NULL OR fecha_nacimiento <'2026-01-01');

-- "fecha_construccion" de SEDE_CANONICA a tipo DATE

ALTER TABLE SEDE_CANONICA 
MODIFY fecha_construccion DATE;

-- En EPOCA_HISTORICA, cambiar "fechas" a NOT NULL

ALTER TABLE EPOCA_HISTORICA 
MODIFY fechas VARCHAR(45) NOT NULL;

-- Cambiar "tiempo_en_calle" de HERMANDAD_PROCESIONAL a INT que necesariamente tiene que ser 
-- mayor a 0

ALTER TABLE HERMANDAD_PROCESIONAL 
MODIFY tiempo_en_calle INT NOT NULL,
ADD CONSTRAINT tiempo_positivo CHECK (tiempo_en_calle > 0);

-- Modificar la tabla HERMANDAD_PROCESIONAL de manera que, por ser hija de HERMANDAD, cuando se elimine o actualice un registro en el padre,
-- ocurra lo mismo en la hija.

ALTER TABLE HERMANDAD_PROCESIONAL
DROP CONSTRAINT fk_nombre_hdad_procesional;
ALTER TABLE HERMANDAD_PROCESIONAL
ADD CONSTRAINT fk_hdad_procesional_nueva 
FOREIGN KEY (nombre_hdad_procesional) 
REFERENCES HERMANDAD (nombre) 
ON DELETE CASCADE 
ON UPDATE CASCADE;

-- Modificar la tabla SEDE_CANONICA para quedarnos solo con el año de construcción

ALTER TABLE SEDE_CANONICA
MODIFY fecha_construccion SMALLINT;

-- Añadir una nueva columna a la tabla PROCESION llamada numero_pasos, que contendrá el número de pasos que componen la procesión. Habrá
-- de ser un natural mayor a 0

ALTER TABLE PROCESION 
ADD COLUMN numero_pasos INT CHECK (numero_pasos > 0);

-- ---------------------------------------------------------------------------------------------------------------------------------------------
-- -----------------------------------------------   Data Manipulation Language   --------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------------------

INSERT IGNORE INTO SEDE_CANONICA (direccion, estilo_arquitectonico_predominante, fecha_construccion) VALUES
('Calle Alfonso XII 27', '', 1248),
('Plaza de San Lorenzo s/n', 'Gótico-Renacentista', 1248),
('Calle San Luis 37', 'Barroco', 1699),
('Calle Pureza 80', 'Gótico-Mudéjar', null),
('Calle Recaredo 19', 'Neobarroco', 1901),
('Calle San Jacinto 43', '', 1775),
('Calle Real de la Carretería 15', 'Barroco', 1761),
('Plaza del Salvador 3', 'Barroco', 1674),
('Plaza de San Gonzalo s/n', 'Moderno', 1942),
('Calle Juan Sebastián Elcano', 'Moderno', null),
('Plaza de San Julián s/n', 'Gótico-Mudéjar', 1350),
('Calle Mateos Gago s/n', 'Gótico-Mudéjar', 1300),
('Calle Feria 105', 'Mudéjar', 1249),
('Calle Adriano 13', 'Barroco', 1761),
('Avenida de la Constitución 13', 'Gótico', 1172),
('Calle Amparo 13', 'Barroco', 1703),
('Calle Evangelista 23', '', 1813),
('Calle Torneo s/n', 'Barroco', 1761),
('Calle Santa Ana s/n', 'Gótico-Mudéjar', 1270),
('Calle Samaniego s/n', 'Moderno', 1960),
('Calle Almirantazgo s/n', 'Barroco', 1700),
('Calle Feria 98', 'Mudéjar', 1350),
('Calle Parlamento de Andalucía', 'Renacentista', 1546),
('Calle Rioja', 'Barroco', 1700),
('Calle Antonio Susillo', 'Regionalista', 1920),
('Calle San Luis 125', 'Barroco', 1730),
('Calle Pagés del Corro 88', 'Popular Trianero', 1800),
('Plaza de San Lorenzo s/n', '', 1248),
('Calle Orfila', 'Barroco', 1716),
('Plaza del Duque s/n', 'Neoclásico', 1850),
('Calle Jesús del Gran Poder 40', 'Barroco', 1690),
('Calle Sol 12', 'Mudéjar', 1380),
('Calle Baños 17', 'Gótico-Mudéjar', 1400),
('Calle Doña María Coronel 1', 'Mudéjar', 1350),
('Próxima a Los Remedios', 'Moderno', 1960),
('Calle Calatrava', 'Barroco', 1600),
('Calle María Auxiliadora 18', 'Neogótico', 1890),
('Calle Cristo del Calvario', 'Barroco', 1700),
('Plaza Jesús de la Redención 0', 'Gótico-Mudéjar', 1350),
('Calle San Fernando 19', 'Neoclásico', 1750),
('Plaza del Museo 9', 'Manierista', 1594),
('Calle Feria 98', 'Mudéjar', 1350),
('Calle Parlamento de Andalucía', 'Renacentista', 1546),
('Calle Rioja', 'Barroco', 1700),
('Calle Antonio Susillo', 'Regionalista', 1925),
('Calle San Luis 125', 'Barroco Sevillano', 1731),
('Calle Pagés del Corro 88', 'Popular', 1850),
('Calle Orfila', 'Barroco', 1716),
('Plaza del Duque s/n', 'Neoclásico', 1860),
('Calle Jesús del Gran Poder 40', 'Barroco', 1690),
('Calle Sol 12', '', 1380),
('Calle Baños 17', 'Gótico-Mudéjar', 1410),
('Calle Doña María Coronel 1', 'Mudéjar', 1350),
('Próxima a Los Remedios', 'Modernista', null),
('Calle Calatrava', 'Barroco', 1680),
('Calle María Auxiliadora 18', 'Neogótico', 1895),
('Calle Cristo del Calvario', 'Barroco', 1705),
('Plaza Jesús de la Redención 0', 'Gótico-Mudéjar', 1355),
('Calle San Fernando 19', 'Neoclásico', 1755),
('Plaza del Museo 9', 'Manierista', 1594),
('Avenida Pedro Romero 10','Moderno',1960),
('Calle Virgen de la Alegría 5','Neoclásico',1780),
('Calle San Luis 37','Barroco',1699);


INSERT INTO EPOCA_HISTORICA (periodo, fechas) VALUES
('Edad Antigua','Siglo XXXV a.C - V'),
('Edad Media', 'Siglos V - XV'),
('Renacimiento', 'Siglo XVI'),
('Barroco', 'Siglos XVII - XVIII'),
('Neoclasicismo', 'Siglo XVIII tardío'),
('Contemporánea', 'Siglos XIX - XXI');

INSERT INTO ROL (categoria) VALUES 
('Nazareno'), ('Costalero'), ('Capataz'), ('Acólito'), ('Músico'), ('Monaguillo'), ('Fiscal'), ('Diputado de tramo');

INSERT INTO PROCESION (motivo, extraordinariedad) VALUES 
('Semana Santa', 'No'), ('Corpus Christi', 'No'), ('Aniversario', 'Sí'), ('Via Crucis', 'No');

INSERT INTO DIA_PROCESIONAL (dia_SS_estival) VALUES 
('Domingo de Ramos'), ('Lunes Santo'), ('Martes Santo'), ('Miércoles Santo'), ('Jueves Santo'), 
('Madrugá'), ('Viernes Santo'), ('Sábado Santo'), ('Domingo de Resurrección'),('Jueves de Corpus'),('Día de la Asunción'),('Lunes de Pentecostés');

INSERT INTO PERSONA (dni, nombre, apellidos, fecha_nacimiento) VALUES
('12345678A', 'Manuel', 'García Pérez', '1985-05-20'),
('23456789B', 'Ana', 'Ramos Ortiz', '1992-11-02'),
('34567890C', 'Antonio', 'Jiménez Ruiz', '1978-03-15'),
('45678901D', 'María', 'López Castro', '2000-07-22'),
('56789012E', 'Francisco', 'Solís Vega', '1965-12-30'),
('67890123F', 'Elena', 'Blanco Sanz', '1998-01-12'),
('78901234G', 'José', 'Naranjo Lara', '1982-06-18'),
('89012345H', 'Rocío', 'Méndez Cruz', '1995-09-05'),
('90123456I', 'David', 'Sánchez Gil', '1988-04-25'),
('01234567J', 'Isabel', 'Torres Mora', '1970-10-10'),
('11223344K', 'Carlos', 'Martínez León', '1990-02-28'),
('22334455L', 'Lucía', 'Fernández Soto', '1987-11-14'),
('33445566M', 'Javier', 'Gómez Herrera', '1993-05-09'),
('44556677N', 'Carmen', 'Vázquez Pardo', '1975-08-21'),
('55667788O', 'Sergio', 'Pascual Domínguez', '2001-03-03'),
('66778899P', 'Patricia', 'Ibáñez Beltrán', '1984-12-12'),
('77889900Q', 'Raúl', 'Cano Moreno', '1999-06-30'),
('88990011R', 'Beatriz', 'Galán Prieto', '1991-01-17'),
('99001122S', 'Marcos', 'Ferrer Calvo', '1968-09-25'),
('10203040T', 'Silvia', 'Duran Suero', '1983-04-14'),
('20304050U', 'Adrián', 'Hidalgo Moya', '1996-10-05'),
('30405060V', 'Marta', 'Rubio Salgado', '1972-07-19'),
('40506070W', 'Hugo', 'Peña Montes', '2004-11-20'),
('50607080X', 'Paula', 'Ortega Rojas', '1989-02-11'),
('60708090Y', 'Daniel', 'Guerrero Jurado', '1995-05-27'),
('70809001Z', 'Irene', 'Castillo Rivas', '1981-08-08'),
('80900112A', 'Álvaro', 'Marín Benítez', '1979-03-22'),
('90011223B', 'Natalia', 'Escribano Font', '1997-12-04'),
('01122334C', 'Ramón', 'Luna Crespo', '1963-01-15'),
('12233445D', 'Gloria', 'Sierra Medina', '1986-06-29');

INSERT INTO HERMANDAD (nombre, cuota_anual, año_fundacional, nombre_hdad_originada, direccion_sede) VALUES
('El Silencio', 40, '1340', null, 'Calle Alfonso XII 27'),
('Gran Poder', 50, '1431', null, 'Plaza de San Lorenzo s/n'),
('La Macarena', 45, '1595', 'La Macarena', 'Calle San Luis 37'),
('Esperanza de Triana', 50, '1418', 'Esperanza de Triana', 'Calle Pureza 80'),
('Los Negritos', 35, '1393', 'Los Negritos', 'Calle Recaredo 19'),
('El Cachorro', 45, '1689', 'El Cachorro', 'Calle San Jacinto 43'),
('La Carretería', 60, '1550', null, 'Calle Real de la Carretería 15'),
('El Amor', 40, '1608', 'El Amor', 'Plaza del Salvador 3'),
('La Estrella', 35, '1560', 'La Estrella', 'Calle San Jacinto 43'),
('San Gonzalo', 30, '1942', 'San Gonzalo', 'Plaza de San Gonzalo s/n'),
('Las Cigarreras', 45, '1563', 'Las Cigarreras', 'Calle Juan Sebastián Elcano'),
('La Hiniesta', 38, '1565', 'La Hiniesta', 'Plaza de San Julián s/n'),
('Santa Cruz', 55, '1904', 'Santa Cruz', 'Calle Mateos Gago s/n'),
('Pasión',79,'1535','Pasión','Plaza del Salvador 3'),
('La Amargura', 48, '1696', 'La Amargura', 'Calle Feria 105'),
('El Baratillo', 42, '1693', null, 'Calle Adriano 13'),
('Virgen de los Reyes', 25, '1946', null, 'Avenida de la Constitución 13'),
('Pastora de Santa Marina', 35, '1703', null, 'Calle Amparo 13'),
('Rocío de Triana', 60, '1813', null, 'Calle Evangelista 23'),
('Rocío de Sevilla', 55, '1951', null, 'Plaza del Salvador 3'),
('Rosario de los Humeros', 25, '1761', null, 'Calle Torneo s/n'),
('Madre de Dios del Rosario', 30, '1814', null, 'Calle Santa Ana s/n'),
('San José Obrero', 30, '1960', null, 'Calle Samaniego s/n'),
('Pura y Limpia del Postigo', 40, '1700', 'Pura y Limpia del Postigo', 'Calle Almirantazgo s/n'),
('La Hiniesta Gloriosa', 38, '1565', 'La Hiniesta Gloriosa', 'Plaza de San Julián s/n');

INSERT INTO NOMENCLATURA_CIUDAD (nombre, comunidad, periodo) VALUES
('Ispal','Tartesia','Edad Antigua'),
('Ispal','Fenicia','Edad Antigua'),
('Hispalis', 'Romana', 'Edad Antigua'),
('Isbiliya', 'Árabe', 'Edad Media'),
('Sevilla','Gitana','Contemporánea'),
('Sevilla', 'Castellana', 'Edad Media');


INSERT INTO HERMANDAD_PROCESIONAL (nombre_hdad_procesional, tiempo_en_calle, advocacion, corte) VALUES
('El Silencio', 4, 'Concepción', 'Silencio'),
('Gran Poder', 7, 'Mayor Dolor y Traspaso', 'Silencio'),
('La Macarena', 12, 'Esperanza', 'Capa'),
('Esperanza de Triana', 12, 'Esperanza', 'Capa'),
('El Cachorro', 8, 'Patrocinio', 'Capa'),
('Los Negritos', 7,'Ángeles','Silencio'),
('La Carretería', 5, 'Mayor Dolor','Silencio'),
('El Amor', 4, 'Socorro','Silencio'),
('La Estrella', 7, 'Estrella', 'Capa'),
('San Gonzalo', 10,'Salud','Capa'),
('Las Cigarreras',7,'Victoria','Capa'),
('La Hiniesta', 10, 'Hiniesta','Capa'),
('Santa Cruz', 5, 'Dolores','Silencio'),
('Pasión',4,'Merced','Silencio'),
('La Amargura',6, 'Amargura', 'Silencio'),
('El Baratillo', 6, 'Caridad','Capa');


INSERT INTO NOMBRE_COLOQUIAL (nombre_coloquial, nombre_oficial) VALUES
('El Señor de Sevilla', 'Gran Poder'),
('La Señora de Sevilla', 'La Macarena'),
('La Rosa de San Gil','La Macarena'),
('La Valiente', 'La Estrella'),
('La Lotera','Rocío de Sevilla'),
('Los Negros','Los Negritos'),
('El Silencio Blanco','La Amargura');

INSERT INTO RESIDIA_EN (nombre_hdad, direccion_sede) VALUES
('El Silencio', 'Calle Feria 98'),
('El Silencio', 'Calle Parlamento de Andalucía'),
('El Silencio','Calle Rioja'),
('La Macarena', 'Calle Antonio Susillo'),
('La Macarena', 'Calle San Luis 125'),
('Esperanza de Triana', 'Calle Pagés del Corro 88'),
('Gran Poder','Plaza de San Lorenzo s/n'),
('La Carretería', 'Calle Orfila'),
('La Carretería','Plaza del Duque s/n'),
('La Carretería','Calle Jesús del Gran Poder 40'),
('El Amor', 'Calle Sol 12'),
('El Amor', 'Calle Baños 17'),
('El Amor', 'Calle Doña María Coronel 1'),
('La Estrella', 'Calle Pagés del Corro 88'),
('La Estrella', 'Próxima a Los Remedios'),
('Las Cigarreras', 'Calle Calatrava'),
('Las Cigarreras', 'Calle María Auxiliadora 18'),
('Las Cigarreras', 'Calle Cristo del Calvario'),
('Las Cigarreras', 'Calle Jesús del Gran Poder 40'),
('Las Cigarreras', 'Calle Doña María Coronel 1'),
('Las Cigarreras', 'Calle Sol 12'),
('Las Cigarreras', 'Plaza Jesús de la Redención 0'),
('Las Cigarreras', 'Calle San Fernando 19'),
('Pasión', 'Plaza del Museo 9'),
('Pasión', 'Plaza de San Julián s/n'),
('Pasión', 'Plaza del Duque s/n'),
('La Amargura', 'Plaza de San Julián s/n');

INSERT INTO IMPLICA (nombre_hdad_implicada, categoria_rol) VALUES
('El Silencio', 'Nazareno'), ('El Silencio', 'Fiscal'), ('El Silencio', 'Acólito'),
('Gran Poder', 'Nazareno'), ('Gran Poder', 'Costalero'), ('Gran Poder', 'Capataz'),
('La Macarena', 'Nazareno'), ('La Macarena', 'Músico'), ('La Macarena', 'Monaguillo'),
('Esperanza de Triana', 'Nazareno'), ('Esperanza de Triana', 'Costalero'),
('Las Cigarreras', 'Músico'), ('Pasión', 'Acólito'), ('La Amargura', 'Diputado de tramo'),
('El Cachorro', 'Nazareno'), ('El Cachorro', 'Costalero'), ('El Cachorro', 'Capataz'), 
('El Cachorro', 'Acólito'), ('El Cachorro', 'Músico'), ('El Cachorro', 'Monaguillo'), 
('El Cachorro', 'Fiscal'), ('El Cachorro', 'Diputado de tramo'),('La Estrella', 'Nazareno'), ('La Estrella', 'Costalero'), ('La Estrella', 'Capataz'), 
('La Estrella', 'Acólito'), ('La Estrella', 'Músico'), ('La Estrella', 'Monaguillo'), 
('La Estrella', 'Diputado de tramo'),('San Gonzalo', 'Nazareno'), ('San Gonzalo', 'Costalero'), ('San Gonzalo', 'Capataz'), 
('San Gonzalo', 'Acólito'), ('San Gonzalo', 'Fiscal'), ('San Gonzalo', 'Diputado de tramo'),
('Rosario de los Humeros', 'Nazareno'),
('Rosario de los Humeros', 'Costalero'),
('Rosario de los Humeros', 'Capataz'),('Rocío de Sevilla', 'Músico'),
('Rocío de Sevilla', 'Diputado de tramo'),
('Rocío de Sevilla', 'Fiscal'),
('Rocío de Sevilla', 'Acólito');

INSERT INTO REALIZA (nombre_hdad_procesional_realiza, motivo_procesional) VALUES
('El Silencio', 'Semana Santa'),
('Gran Poder', 'Semana Santa'),
('Gran Poder', 'Aniversario'),
('La Macarena', 'Semana Santa'),
('La Macarena', 'Aniversario'),
('La Macarena', 'Via Crucis'),
('Esperanza de Triana', 'Semana Santa'),
('Esperanza de Triana', 'Aniversario'),
('Esperanza de Triana', 'Via Crucis'),
('El Cachorro', 'Semana Santa'),
('Pasión', 'Semana Santa'),
('Pasión', 'Via Crucis'),
('La Hiniesta', 'Semana Santa'),
('La Hiniesta', 'Via Crucis'),
('La Hiniesta', 'Aniversario'),
('La Amargura', 'Semana Santa');

INSERT INTO ES_HERMANO_DE (numero_hermano, nombre_hdad_es_hermano, dni_hermano) VALUES
('1', 'El Silencio', '12345678A'),
('542', 'Gran Poder', '23456789B'),
('1200', 'La Macarena', '34567890C'),
('342', 'Esperanza de Triana', '45678901D'),
('15', 'Pasión', '56789012E'),
('889', 'La Estrella', '67890123F'),
('23', 'El Baratillo', '78901234G'),
('102', 'La Amargura', '89012345H'),
('67', 'San Gonzalo', '90123456I'),
('5', 'Los Negritos', '01234567J'),
('12', 'Virgen de los Reyes', '11223344K'),
('45', 'Pastora de Santa Marina', '33445566M'),
('3021', 'Rocío de Triana', '44556677N'),
('150', 'Rocío de Sevilla', '55667788O'),
('560', 'Rocío de Sevilla', '66778899P'),
('22', 'Rosario de los Humeros', '77889900Q'),
('115', 'Madre de Dios del Rosario', '88990011R'),
('90', 'San José Obrero', '99001122S'),
('8', 'Pura y Limpia del Postigo', '10203040T'),
('2500', 'La Hiniesta Gloriosa', '70809001Z'),
('140', 'Pastora de Santa Marina', '80900112A'),
('33', 'Rocío de Sevilla', '90011223B'),
('10', 'San José Obrero', '12233445D');

INSERT INTO PARTICIPA (dni_persona_participante, dia_SS_estival, motivo_procesion, rol_participacion, importe_papeleta_sitio) VALUES
('12345678A', 'Madrugá', 'Semana Santa', 'Nazareno', 30),
('23456789B', 'Madrugá', 'Semana Santa', 'Fiscal', 50),
('34567890C', 'Madrugá', 'Semana Santa', 'Monaguillo', 15),
('45678901D', 'Madrugá', 'Semana Santa', 'Costalero', 0),
('56789012E', 'Jueves Santo', 'Semana Santa', 'Acólito', 20),
('67890123F', 'Domingo de Ramos', 'Semana Santa', 'Nazareno', 25),
('78901234G', 'Miércoles Santo', 'Semana Santa', 'Costalero', 0),
('89012345H', 'Domingo de Ramos', 'Semana Santa', 'Diputado de tramo', 35),
('90123456I', 'Lunes Santo', 'Semana Santa', 'Músico', 0),
('01234567J', 'Jueves Santo', 'Semana Santa', 'Nazareno', 25),
('20304050U', 'Madrugá', 'Semana Santa', 'Fiscal', 50),
('11223344K', 'Domingo de Resurrección', 'Semana Santa', 'Nazareno', 25),
('22334455L', 'Lunes Santo', 'Semana Santa', 'Costalero', 0),
('33445566M', 'Jueves de Corpus', 'Corpus Christi', 'Acólito', 10),
('44556677N', 'Lunes de Pentecostés', 'Aniversario', 'Nazareno', 40),
('55667788O', 'Martes Santo', 'Semana Santa', 'Músico', 0),
('66778899P', 'Miércoles Santo', 'Semana Santa', 'Nazareno', 30),
('77889900Q', 'Viernes Santo', 'Semana Santa', 'Costalero', 0),
('88990011R', 'Sábado Santo', 'Semana Santa', 'Fiscal', 45),
('99001122S', 'Jueves Santo', 'Semana Santa', 'Capataz', 0),
('10203040T', 'Madrugá', 'Semana Santa', 'Nazareno', 35),
('20304050U', 'Día de la Asunción', 'Aniversario', 'Acólito', 15),
('30405060V', 'Viernes Santo', 'Via Crucis', 'Nazareno', 20),
('60708090Y', 'Lunes Santo', 'Semana Santa', 'Costalero', 0),
('70809001Z', 'Sábado Santo', 'Semana Santa', 'Nazareno', 30),
('01122334C', 'Jueves de Corpus', 'Corpus Christi', 'Fiscal', 40);

INSERT INTO DESARROLLO_DURANTE (periodo_epoca, direccion_sede) VALUES
('Edad Media', 'Plaza de San Lorenzo s/n'),
('Edad Media', 'Calle Pureza 80'),
('Renacimiento', 'Calle Alfonso XII 27'),
('Barroco', 'Calle San Luis 37'),
('Barroco', 'Calle Real de la Carretería 15'),
('Barroco', 'Plaza del Salvador 3'),
('Contemporánea', 'Plaza de San Gonzalo s/n'),
('Contemporánea', 'Calle Recaredo 19');

INSERT INTO detalle_nomenclatura (nombre_ciudad, comunidad_ciudad, tipo_fuente, etimologia) VALUES
('Ispal', 'Fenicia', 'Arqueológica', 'Restos de factoría comercial'),
('Ispal', 'Fenicia', 'Numismática', 'Inscripciones en monedas'),
('Ispal', 'Tartesia', 'Manuscrito', 'Textos que la describen como la capital de la llanura.'),
('Ispal', 'Tartesia', 'Tradición Oral', 'Leyenda que atribuye la fundación a Hispalo.'),
('Hispalis', 'Romana', 'Epigráfica', 'Lápidas del foro romano'),
('Hispalis', 'Romana', 'Arqueológica', 'Cimentaciones de las murallas'),
('Hispalis', 'Romana', 'Literatura Clásica', 'Menciones de Plinio el Viejo'),
('Isbiliya', 'Árabe', 'Crónica Medieval', 'Relatos de Al-Razi'),
('Isbiliya', 'Árabe', 'Poética', 'Versos de poetas andalusíes'),
('Isbiliya', 'Árabe', 'Cartográfica', 'Mapas de Al-Idrisi'),
('Sevilla', 'Castellana', 'Documental Real', 'Privilegios otorgados por Alfonso X'),
('Sevilla', 'Castellana', 'Tradición Popular', 'Coplería medieval'),
('Sevilla', 'Gitana', 'Lirica Flamenca', 'Letras de cantes antiguos'),
('Sevilla', 'Gitana', 'Etnográfica', 'Asentamiento histórico en el barrio de Triana.'),
('Hispalis', 'Romana', 'Geografía Antigua', 'Mapas de Ptolomeo');

SET SQL_SAFE_UPDATES = 0;

update SEDE_CANONICA
set estilo_arquitectonico_predominante = if(estilo_arquitectonico_predominante = '', 'Estilo no definido', estilo_arquitectonico_predominante)
where estilo_arquitectonico_predominante = '';

SET SQL_SAFE_UPDATES = 1; -- Esto se realiza por que no puedo actualizar registros que no utilicen la PK en WHERE.

-- ---------------------------------------------------------------------------------------------------------------------------------------------
-- --------------------------------------------------------------  Consultas  ------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------------------------------------------

-- Devolver el nombre de todas aquellas hermandades con nombre coloquial cuyo nombre oficial comience por "la" o cuyo nombre coloquial termine por "la"
-- y ordenar alfabéticamente por nombre oficial.

select nombre_oficial
from nombre_coloquial
where nombre_oficial like 'La%' or nombre_coloquial like '%la'
order by nombre_oficial;

-- Para hermandades que hayan residido previamente en otra/s sede/s distinta/s, devolver todos los datos solo si la cuota anual está entre 45 y 50, ambos 
-- inclusive. Ordenar por cuota anual ascendentemente y por año fundacional descendentemente

select *
from hermandad inner join residia_en on hermandad.nombre = residia_en.nombre_hdad
where cuota_anual between 45 and 50
order by cuota_anual asc,año_fundacional;

-- Devolver los registros de HERMANDAD cuyo número de hermanos no sea
-- superado por ninguna otra hermandad.

select *
from hermandad
where nombre in (select nombre_hdad_es_hermano 
                 from es_hermano_de
                 group by nombre_hdad_es_hermano
                 having count(*) = (select count(*) 
                                    from es_hermano_de 
                                    group by nombre_hdad_es_hermano 
                                    order by 1 desc 
                                    limit 1));
                
-- Número de roles distintos participantes en cada día de Semana Santa o estival, limitándonos solo a aquellas jornadas con más de 3 personas

select dia_SS_estival, count(distinct rol_participacion) as roles_distintos, count(dni_persona_participante) as total_personas
from participa
group by dia_SS_estival
having total_personas > 3;

-- Cómputo del importe por papeleta por día de Semana Santa o día estival

select dia_SS_estival,sum(importe_papeleta_sitio) as Cómputo_papeletas
from dia_procesional natural join participa
group by dia_SS_estival;

-- Devolver los datos de las personas que son hermanas de alguna hermandad y que no participan en ninguna procesión

select *
from persona p inner join es_hermano_de e on p.dni = e.dni_hermano
where dni not in (select dni_persona_participante from participa);

-- Devolver los datos de los datos de la tabla participa para las personas que salgan en procesión extraordinaria y cuyo rol sea o acólito
-- o nazareno, ordenados los registros por el importe de papeleta descendentemente

select *
from participa
where motivo_procesion in (select motivo from procesion where extraordinariedad = 'Sí') and rol_participacion in ("Acólito","Nazareno")
order by importe_papeleta_sitio desc;

-- Devolver la fecha de construcción y la dirección de la sede canónica, para aquellas donde el estilo arquitectonico predominante sea 
-- el gótico o un subgénero de este. En fechas donde no haya registro, mostrar "No se conoce"

select direccion, coalesce(fecha_construccion,"No se conoce") as fecha_construccion
from sede_canonica
where estilo_arquitectonico_predominante like "%Gótico%";

-- Para las hermandades, clasificar la cantidad de cuota anual en "precio bajo" si son menores o iguales a 40;"precio medio" si están entre 40 y
-- 60; y "precio alto" si son mayores o iguales a 60. Devolver, por tanto, nombre de las hermandades y precio de las cuotas anuales y ordernar 
-- alfabéticamente por nombre

select nombre, cuota_anual,
    case 
        when cuota_anual <= 40 then 'precio bajo' 
        when cuota_anual >= 60 then 'precio alto' 
        else'precio medio' 
    end as coste_cuotas
from hermandad
order by nombre;

-- Devolver nombre de hermandades procesionales de menos de 10 horas junto con comunidades históricas con las que han coexistido a lo largo 
-- del tiempo, así como el nombre que le daban a la ciudad de Sevilla y cada origen etimológico.

select h2.nombre,comunidad_ciudad,nombre_ciudad,tipo_fuente,etimologia
from hermandad_procesional h1 inner join  hermandad h2 on h1.nombre_hdad_procesional = h2.nombre
inner join sede_canonica s on h2.direccion_sede = s.direccion
inner join desarrollo_durante d on s.direccion = d.direccion_sede
inner join epoca_historica e on d.periodo_epoca = e.periodo
inner join nomenclatura_ciudad n using(periodo)
inner join detalle_nomenclatura d1 on n.nombre = d1.nombre_ciudad and n.comunidad = d1.comunidad_ciudad
where tiempo_en_calle<10;

-- Devolver nombre de hermandades procesionales que impliquen todos los roles menos 'Músico' y 'Monaguillo'

select h1.nombre_hdad_procesional as Nombre  
from implica i inner join hermandad h on i.nombre_hdad_implicada = h.nombre 
inner join hermandad_procesional h1 on h.nombre = h1.nombre_hdad_procesional
where categoria_rol not in ('Músico','Monaguillo')
group by nombre_hdad_procesional
having count(distinct i.categoria_rol) = (select count(distinct categoria) from rol  where categoria not in ('Músico','Monaguillo'));

-- Datos de aquellas sedes para las cuales no existe ninguna nomenclatura de la ciudad que no esté vinculada a dicha sede a través de su 
-- periodo histórico

select *
from sede_canonica s
where not exists (select *
                  from nomenclatura_ciudad n
                  where not exists (select *
									from desarrollo_durante d
                                    where d.direccion_sede = s.direccion and d.periodo_epoca = n.periodo));
                                    
-- Devolver la fecha de nacimiento de aquellas personas que hayan nacido después de alguna de las personas cuyo DNI termina en A

select fecha_nacimiento
from persona
where year(fecha_nacimiento) > any (select year(fecha_nacimiento) from persona where dni like '%A');

-- Construye una vista para recopilar información de una hermandad, su sede y su nombre coloquial y devuelve datos para el estilo barroco

create view vista_resumen_hermandades as
select h.nombre as nombre_oficial, nc.nombre_coloquial, h.año_fundacional, s.direccion as sede, s.estilo_arquitectonico_predominante as estilo
from hermandad h inner join nombre_coloquial nc on h.nombre = nc.nombre_oficial inner join sede_canonica s on h.direccion_sede = s.direccion;

select *
from vista_resumen_hermandades
where estilo = 'Barroco';

-- Clasifica en una nueva columna la naturaleza de los pueblos que dieron diversas nomenclaturas a Sevilla, según si fueron antes o después
-- de los romanos.

select *,
if( comunidad_ciudad like '%fenicia%' or comunidad_ciudad like '%tartesia%','Pueblos prerromanos','Pueblos posromanos') 
as naturaleza_comunidad
from detalle_nomenclatura;